{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "Wallet API",
    "description": "REST API Application",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    {
      "url": "http://localhost:3030"
    },
    {
      "url": "https://wallet-api-goit.onrender.com"
    }
  ],
  "tags": [
    {
      "name": "Google Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Users",
      "description": "Authorization endpoints"
    },
    {
      "name": "Transactions",
      "description": "Transactions endpoints"
    },
    {
      "name": "Categories",
      "description": "Categories endpoints"
    },
    {
      "name": "Statistics",
      "description": "Statistics endpoints"
    }
  ],
  "paths": {
    "/api/auth/google": {
      "get": {
        "tags": ["Google Auth"],
        "summary": "Google Auth",
        "parameters": [],
        "responses": {
          "302": {
            "description": "Redirects the user to the Google sign-in page",
            "headers": {},
            "content": {}
          }
        },
        "description": "This endpoint redirects the user to the Google sign-in page in order to authenticate. The redirect URL includes query parameters that specify the Google OAuth2 client ID, the redirect URI of the app's Google Auth Redirect endpoint, the scopes for which the app is requesting authorization, and the response type, access type, and prompt type for the authorization request."
      }
    },
    "/api/auth/google-redirect": {
      "get": {
        "tags": ["Google Auth"],
        "summary": "Google Auth Redirect",
        "parameters": [],
        "responses": {
          "302": {
            "description": "Redirects the user to the app after authenticating with Google",
            "headers": {},
            "content": {}
          }
        },
        "description": "This endpoint is called after the user has authenticated with Google. It retrieves an authorization code from the query parameters, exchanges it for an access token using the Google OAuth2 API, and uses the access token to retrieve the user's email address from the Google UserInfo API. It then checks if a user with the given email address already exists in the database. If so, and the user is of type 'password auth', the user is redirected to the app's frontend. If the user exists and is of type 'google auth', their token and password are updated with the new access token. If the user does not exist, a new user is created in the database with the user's name, email, and access token, and the user is redirected to the app's frontend. The access token and name are included in the redirect URL as query parameters."
      }
    },

    "/api/users/register": {
      "post": {
        "tags": ["Users"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password", "name"],
                "properties": {
                  "email": {
                    "type": "string",
                    "description": "User email",
                    "example": "user@mail.com"
                  },
                  "password": {
                    "type": "string",
                    "description": "User password",
                    "example": "123&Qwerty"
                  },
                  "name": {
                    "type": "string",
                    "example": "User"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "User created"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "name": "User",
                        "email": "user@mail.com"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Invalid request body"
                    }
                  }
                }
              }
            }
          },

          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Provided email already in use"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/users/login": {
      "post": {
        "tags": ["Users"],
        "summary": "User login",
        "parameters": [],
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["email", "password"],
                "properties": {
                  "email": {
                    "type": "string",
                    "description": "User email",
                    "example": "user@mail.com"
                  },
                  "password": {
                    "type": "string",
                    "description": "User password",
                    "example": "123&Qwerty"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "You have successfully logged in"
                    },
                    "token": {
                      "type": "string",
                      "description": "User token",
                      "example": "token"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "email": "user@mail.com",
                        "name": "User",
                        "id": "User ID"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Invalid request body"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Email or password is wrong"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/api/users/logout": {
      "post": {
        "tags": ["Users"],
        "summary": "User logout",

        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {}
          },

          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/api/users/current": {
      "get": {
        "tags": ["Users"],
        "summary": "Current user",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Successful operation"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "email": "user@mail.com",
                        "name": "User",
                        "balance": 100500
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/api/transactions": {
      "post": {
        "tags": ["Transactions"],
        "summary": "Create a new transaction",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "requestBody": {
          "description": "Transaction's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["amount", "income"],
                "properties": {
                  "income": {
                    "income": "boolean",
                    "example": true
                  },
                  "category": {
                    "type": "string",
                    "example": "other expenses"
                  },
                  "comment": {
                    "type": "string",
                    "example": "Commentary transaction"
                  },
                  "amount": {
                    "type": "number",
                    "example": "100500"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Transaction created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Transaction success created"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "category": "other expenses",
                        "amount": 100500,
                        "commment": "Commentary transaction",
                        "income": true
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Missing required field"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Transactions"],
        "summary": "Get all transactions",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "type": "object",
                "example": {
                  "data": [
                    {
                      "_id": "6430ff509a0e4eea095df1e9",
                      "owner": "UserId",
                      "date": {
                        "time": 1680966033359,
                        "day": 8,
                        "month": 3,
                        "year": 2022
                      },
                      "income": true,
                      "category": "other expenses",
                      "comment": "Transactions comment",
                      "amount": 5000
                    },
                    {
                      "_id": "6430ff509a0e4eea095df1e9",
                      "owner": "UserId",
                      "date": {
                        "time": 1680966033359,
                        "day": 8,
                        "month": 3,
                        "year": 2022
                      },
                      "income": false,
                      "category": "other expenses",
                      "comment": "Transactions comment",
                      "amount": 3000
                    },
                    {
                      "_id": "6430ff509a0e4eea095df1e9",
                      "owner": "UserId",
                      "date": {
                        "time": 1680966033359,
                        "day": 8,
                        "month": 3,
                        "year": 2022
                      },
                      "income": false,
                      "category": "other expenses",
                      "comment": "Transactions comment",
                      "amount": 7000
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/api/transactions/{id}": {
      "get": {
        "tags": ["Transactions"],
        "summary": "Get transaction by ID",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "description": "Transaction ID",
            "name": "id"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Successful operation"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "_id": "64311b4d4f493b571dad6681",
                        "amount": 4500,
                        "income": false,
                        "category": "car",
                        "comment": "Transactions comment",
                        "date": {
                          "time": 1680966033359,
                          "day": 8,
                          "month": 3,
                          "year": 2022
                        },
                        "owner": "6430f4be10f5cac93a1400fa",
                        "createdAt": "2023-04-08T07:44:13.522Z",
                        "updatedAt": "2023-04-08T08:18:29.120Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["Transactions"],
        "summary": "Update transaction",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "description": "Transaction ID",
            "name": "id"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "requestBody": {
          "description": "Transaction's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "type": {
                    "income": "boolean",
                    "example": false
                  },
                  "category": {
                    "type": "string",
                    "example": "car"
                  },
                  "comment": {
                    "type": "string",
                    "example": "Commentary transaction"
                  },
                  "amount": {
                    "type": "number",
                    "example": "4500"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Success update"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "_id": "64311b4d4f493b571dad6681",
                        "amount": 4500,
                        "income": false,
                        "category": "car",
                        "comment": "Transactions comment",
                        "date": {
                          "time": 1680966033359,
                          "day": 8,
                          "month": 3,
                          "year": 2022
                        },
                        "owner": "6430f4be10f5cac93a1400fa",
                        "createdAt": "2023-04-08T07:44:13.522Z",
                        "updatedAt": "2023-04-08T08:18:29.120Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Transactions"],
        "summary": "Delete transaction",
        "parameters": [
          {
            "in": "path",
            "required": true,
            "description": "Transaction ID",
            "name": "id"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Transaction removed"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/categories": {
      "get": {
        "tags": ["Categories"],
        "summary": "Get all categories",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Successful operation"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": [
                        { "id": "1", "category": "other expenses" },
                        { "id": "2", "category": "other expenses" },
                        { "id": "3", "category": "other expenses" }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/statistics": {
      "get": {
        "tags": ["Statistics"],
        "summary": "Get all statistics",
        "parameters": [
          {
            "in": "query",
            "description": "Year",
            "name": "year"
          },
          {
            "in": "query",
            "description": "Month",
            "name": "month"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "The token issued to the current user",
            "required": true,
            "type": "string"
          }
        ],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "responses message",
                      "example": "Successful operation"
                    },
                    "data": {
                      "type": "object",
                      "description": "responses data",
                      "example": {
                        "totalIncome": 1000,
                        "totalExpense": 5000,
                        "expenseByCategory": {
                          "main expenses": 0,
                          "products": 1000,
                          "car": 0,
                          "self care": 1000,
                          "child care": 0,
                          "household products": 1000,
                          "education": 1000,
                          "leisure": 1000,
                          "other expenses": 0
                        },
                        "incomeByCategory": {
                          "main expenses": 0,
                          "products": 0,
                          "car": 500,
                          "self care": 0,
                          "child care": 0,
                          "household products": 0,
                          "education": 0,
                          "leisure": 0,
                          "other expenses": 500
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User unauthorized"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Internal server error"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "example": "6193b4f36a453535c5b9cfe3"
          },
          "token": {
            "type": "string",
            "example": "User token"
          },
          "email": {
            "type": "string",
            "example": "user@mail.com"
          },
          "name": {
            "type": "string",
            "example": "User"
          },
          "balance": {
            "type": "Number",
            "example": 100500
          },
          "password": {
            "type": "string",
            "example": "$2a$10$7/ZJpglAhQnMKAmshacmSe.Gx8pMni4jDIVPykJ9.gGobeZCsYqou"
          },

          "createdAt": {
            "type": "string",
            "example": "2023-04-08T05:45:49.483+00:00"
          },
          "updatedAt": {
            "type": "string",
            "example": "2023-04-08T05:45:49.483+00:00"
          }
        }
      },
      "Transaction": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "String",
            "example": "6193b4f36a453535c5b9cfe3"
          },
          "owner": {
            "type": "String",
            "example": "UserId"
          },
          "date": {
            "type": "Object",
            "example": {
              "time": 1680966033359,
              "day": 8,
              "month": 3,
              "year": 2022
            }
          },
          "type": {
            "type": "boolean",
            "example": "true"
          },
          "category": {
            "type": "string",
            "example": "other expenses"
          },
          "comment": {
            "type": "String",
            "example": "User commentary"
          },
          "amount": {
            "type": "number",
            "example": 100500
          },
          "createdAt": {
            "type": "string",
            "example": "2023-04-08T05:45:49.483+00:00"
          },
          "updatedAt": {
            "type": "string",
            "example": "2023-04-08T05:45:49.483+00:00"
          }
        }
      },

      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "1"
          },
          "category": {
            "type": "string",
            "example": "other expenses"
          }
        }
      },
      "Statistics": {
        "type": "object",
        "properties": {
          "totalIncome": {
            "type": "Number",
            "example": 1000
          },
          "totalExpense": {
            "type": "Number",
            "example": 500
          },
          "expenseByCategory": {
            "type": "Object",
            "example": {
              "main expenses": 0,
              "products": 0,
              "car": 0,
              "self care": 0,
              "child care": 0,
              "household products": 0,
              "education": 0,
              "leisure": 0,
              "other expenses": 0
            }
          },
          "incomeByCategory": {
            "type": "Object",
            "example": {
              "main expenses": 0,
              "products": 0,
              "car": 0,
              "self care": 0,
              "child care": 0,
              "household products": 0,
              "education": 0,
              "leisure": 0,
              "other expenses": 0
            }
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
